# Generated by Django 4.2 on 2023-05-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('hrs', models.IntegerField(verbose_name='Duration')),
            ],
        ),
    ]
