# Generated by Django 4.1.7 on 2023-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('doc', models.DateTimeField(auto_now_add=True)),
                ('doe', models.DateField(auto_now=True)),
                ('dop', models.DateField(verbose_name='Publish Date')),
                ('published', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='blog.categorymodel')),
            ],
        ),
    ]
