# Generated by Django 4.2 on 2023-07-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_socialmedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
