# Generated by Django 4.1.7 on 2023-02-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
