# Generated by Django 4.1.7 on 2023-03-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_pydictmodels_pydictmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PytupleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('post_date', models.DateField()),
                ('publish', models.BooleanField()),
            ],
        ),
    ]
